### PR TITLE
Added "!roll" functionality

### PR DESCRIPTION
**Pull request by wazzletunk**
This change is [Reviewable](https://reviewable.io/reviews/threedliams/callbackbot/1)

### CODE REVIEW

**Comment by threedliams** [comment]
*[narcov.py, line 481 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv8xePymnSzHxnAGX8w:-Kv8xePymnSzHxnAGX8x:b-72a818) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L481)):*
> ```Python
>         "!magic": magic,
>         "!poll": createPoll,
>         "!roll": roll
> ```

Can you add a trailing comma here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/threedliams/callbackbot/1)*

**Comment by threedliams** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[narcov.py, line 424 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv9-2guqY3bfEFLyQ6X:-Kv9-2guqY3bfEFLyQ6Y:b-o8j8vc) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L424)):*
> ```Python
>     return messageText
> 
> #!roll 1d4 10d20
> ```

Can you format this like the rest of the function comments?

---

*[narcov.py, line 427 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv8ylx8NODNv3d0Df_w:-Kv8ylx8NODNv3d0Df_x:bx0ku6x) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L427)):*
> ```Python
> def roll(tokenizedMessage, message):
>     random.seed()
>     tokenizedMessage.remove("!roll")
> ```

Instead of removing this from the tokenized message, you should remove this from the dieList after you copy it over. Python passes everything by reference, not value (annoying) and we don't want the tokenized message to change

---

*[narcov.py, line 429 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv8zoUgAIY2COFJ7aKv:-Kv8zoUgAIY2COFJ7aKw:bvs2lf3) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L429)):*
> ```Python
>     tokenizedMessage.remove("!roll")
>     errorMessage = "Format: '!roll AdB...' where A is the number of rolls of a B-sided dice. Up to 6 types at a time, 5 rolls each."
>     dieList = tokenizedMessage
> ```

You should copy this array if you intend on modifying it, as assignment is done by reference so you'll still be touching the original array. See https://stackoverflow.com/questions/19341365/setting-two-arrays-equal

---

*[narcov.py, line 430 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv9-HOwoF-p0lJD14mU:-Kv9-HOwoF-p0lJD14mV:b8nns1p) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L430)):*
> ```Python
>     errorMessage = "Format: '!roll AdB...' where A is the number of rolls of a B-sided dice. Up to 6 types at a time, 5 rolls each."
>     dieList = tokenizedMessage
>     if((''.join(dieList).translate(str.maketrans('0123456789d','           '))).strip() != ''):
> ```

This is a clever way of doing this, but it is a bit unusual, so you should add a comment explaining it above

---

*[narcov.py, line 433 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv9-UhdwV15fxD0bnov:-Kv9-UhdwV15fxD0bnow:bx1wto4) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L433)):*
> ```Python
>         return errorMessage
>     rollTotal = 0
>     rollText = "Result of rolls :"
> ```

Did you intend for the space to be before or after the colon?

---

*[narcov.py, line 437 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv90QwHGOYiG55uVRZo:-Kv90QwIGzOoX-jdJO8h:binltag) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L437)):*
> ```Python
>     for die in dieList:
>         attempt = die.split('d')
>         if(len(attempt)!=2):
> ```

Is it possible to move these 2 failure conditions somewhere outside of the calculation? That would avoid spending time unnecessarily blocking on a long list of die when one of them is going to fail out. If you don't think it's worth it or if there's no good way that's fine, but we want to avoid spending too much time in blocking functions since I think that's what's causing narcov to occasionally die

---

*[narcov.py, line 442 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv8yFPyvxPusOIvIbtB:-Kv8yFPyvxPusOIvIbtC:beu4kfd) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L442)):*
> ```Python
>             return errorMessage
>         rollText += " ("
>         #attempt = list(die)
> ```

Can you remove this leftover comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/threedliams/callbackbot/1)*

**Comment by threedliams** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---

*[narcov.py, line 424 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv9-2guqY3bfEFLyQ6X:-KvOJBtMNLZ6VU3FPdZ5:bb7k0qh) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L424)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

Can you format this like the rest of the function comments?
</blockquote></details>

lgtm

---

*[narcov.py, line 427 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv8ylx8NODNv3d0Df_w:-KvOJQDWKITZM9gXy3WL:bb7k0qh) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L427)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

Instead of removing this from the tokenized message, you should remove this from the dieList after you copy it over. Python passes everything by reference, not value (annoying) and we don't want the tokenized message to change
</blockquote></details>

lgtm

---

*[narcov.py, line 429 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv8zoUgAIY2COFJ7aKv:-KvOJS8sxTNT-Tm39o92:bb7k0qh) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L429)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

You should copy this array if you intend on modifying it, as assignment is done by reference so you'll still be touching the original array. See https://stackoverflow.com/questions/19341365/setting-two-arrays-equal
</blockquote></details>

lgtm

---

*[narcov.py, line 430 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv9-HOwoF-p0lJD14mU:-KvOJURZkYM32sJXhx49:b-qtsuty) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L430)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

This is a clever way of doing this, but it is a bit unusual, so you should add a comment explaining it above
</blockquote></details>

ok, no longer relevant

---

*[narcov.py, line 433 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv9-UhdwV15fxD0bnov:-KvOJZIv3kxeShp6yDtx:bb7k0qh) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L433)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

Did you intend for the space to be before or after the colon?
</blockquote></details>

lgtm

---

*[narcov.py, line 437 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv90QwHGOYiG55uVRZo:-KvOJjQwMuw9wJp2DVi4:b-sjsgvz) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L437)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

Is it possible to move these 2 failure conditions somewhere outside of the calculation? That would avoid spending time unnecessarily blocking on a long list of die when one of them is going to fail out. If you don't think it's worth it or if there's no good way that's fine, but we want to avoid spending too much time in blocking functions since I think that's what's causing narcov to occasionally die
</blockquote></details>

looks great, very nicely done with the regex!

---

*[narcov.py, line 442 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv8yFPyvxPusOIvIbtB:-KvOJoEz3XTLHiSClLtx:bb7k0qh) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L442)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

Can you remove this leftover comment?
</blockquote></details>

lgtm

---

*[narcov.py, line 481 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv8xePymnSzHxnAGX8w:-Kv91PuY4DXxnYbSehR8:bb6ywmx) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L481)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

Can you add a trailing comma here?
</blockquote></details>

LGTM

---

*[narcov.py, line 449 at r2](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-KvOJpUYJBYO-14v5DbO:-KvOJpUYJBYO-14v5DbP:b-jz4cjt) ([raw file](https://github.com/threedliams/callbackbot/blob/6b8648c4761305cf4d2940e663d43ca5af3d6e2e/narcov.py#L449)):*
> ```Python
>     for die in dieList:
>         attempt = die.split('d')
>         #if(len(attempt)!=2):
> ```

everything looks perfect, just a little bit of leftover commented out code and we'll be good to go. thanks for taking the time to fix everything!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/threedliams/callbackbot/1)*

**Comment by threedliams** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 9 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/threedliams/callbackbot/1)*

**Comment by threedliams** [comment]
*[narcov.py, line 437 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv90QwHGOYiG55uVRZo:-KvOL-lEIdhup7IgmUy-:b3o8qti) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L437)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

looks great, very nicely done with the regex!
</blockquote></details>

sorry, forgot to resolve this

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/threedliams/callbackbot/1)*

**Comment by wazzletunk** [comment]
Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/threedliams/callbackbot/1)*

**Comment by wazzletunk** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[narcov.py, line 424 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv9-2guqY3bfEFLyQ6X:-KvOWpBZdoa6faM4Wh5C:b-896fix) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L424)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

lgtm
</blockquote></details>

Done.

---

*[narcov.py, line 427 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv8ylx8NODNv3d0Df_w:-KvOWyROzI9Giv_HSByZ:b-896fix) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L427)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

lgtm
</blockquote></details>

Done.

---

*[narcov.py, line 429 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv8zoUgAIY2COFJ7aKv:-KvOWywjswAjwpfm5Qzw:b-896fix) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L429)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

lgtm
</blockquote></details>

Done.

---

*[narcov.py, line 430 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv9-HOwoF-p0lJD14mU:-KvOWzH2Aa-bfAO073u6:b-896fix) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L430)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

ok, no longer relevant
</blockquote></details>

Done.

---

*[narcov.py, line 433 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv9-UhdwV15fxD0bnov:-KvOX-ivo0b8dezomhR1:b-896fix) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L433)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

lgtm
</blockquote></details>

Done.

---

*[narcov.py, line 442 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv8yFPyvxPusOIvIbtB:-KvOX0BdrbJ-l4RQE8wl:b-896fix) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L442)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

lgtm
</blockquote></details>

Done.

---

*[narcov.py, line 481 at r1](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-Kv8xePymnSzHxnAGX8w:-KvOX0uXjVeujk4D5_kk:b-896fix) ([raw file](https://github.com/threedliams/callbackbot/blob/a7a17e0fa9f6e8279cd7b63221f9c27666ab6f37/narcov.py#L481)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

LGTM
</blockquote></details>

Done.

---

*[narcov.py, line 449 at r2](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-KvOJpUYJBYO-14v5DbO:-KvOX2V79-4cPevLb3M6:b-896fix) ([raw file](https://github.com/threedliams/callbackbot/blob/6b8648c4761305cf4d2940e663d43ca5af3d6e2e/narcov.py#L449)):*
<details><summary><i>Previously, threedliams wrote…</i></summary><blockquote>

everything looks perfect, just a little bit of leftover commented out code and we'll be good to go. thanks for taking the time to fix everything!
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/threedliams/callbackbot/1)*

**Comment by threedliams** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/threedliams/callbackbot/1#-:-KvOXgZS_bCYtYnt4b9N:bnfp4nl)*

**Pull request merged**
